repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.47.0
    hooks:
      - id: eslint
        types: [file] # override default `types: [javascript]`
        types_or: [ts, tsx]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier
        types: [file] # override default `types: [javascript]`
        types_or: [ts, tsx]
